verify_signatures: false

# We ignore the following git hooks provided by overcommit for now
PostCheckout:
  ALL:
    enabled: false
CommitMsg:
  ALL:
    enabled: false

# Custom options for Dahlia repository
PreCommit:

  BundleCheck:
    enabled: true

  # Ignore all Overcommit default options
  ALL:
    enabled: false
    on_warn: fail

  # Enable explicitly each desired pre commit check
  RuboCop:
    enabled: true
    description: 'Analyzing with Rubocop'
    required_executable: 'rubocop'

  RailsSchemaUpToDate:
    enabled: true
    description: 'Checking if database schema is up to date'
    include:
      - 'db/migrate/*.rb'
      - 'db/schema.rb'
      - 'db/structure.sql'

  YamlSyntax:
    enabled: true
    description: 'Checking YAML syntax'

  RailsBestPractices:
    enabled: true
    description: 'Checking Rails best practices'

  CoffeeLint:
    enabled: true
    description: 'Analyzing with CoffeeLint'
    required_executable: 'coffeelint'
    install_command: 'npm install'

  TrailingWhitespace:
    enabled: true
    description: 'Checking for trailing whitespace'
    exclude:
      - 'spec/cassettes/**/*.yml'
      - 'app/assets/**/*.svg'
      - 'lib/assets/bower_components/**/*'

  CustomScript:
    enabled: true
    required_executable: './bin/overcommit-pre-commit'
