---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=dave%40mohcd.com.full&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 28 Jul 2016 01:00:32 GMT
      Strict-Transport-Security:
      - max-age=10886400; includeSubDomains; preload
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; font-src https:
        data:; report-uri /_/ContentDomainCSPNoAuth?type=login'
      Set-Cookie:
      - BrowserId=URYhQHdQSvuppZr2aLLDWg;Path=/;Domain=.salesforce.com;Expires=Mon,
        26-Sep-2016 01:00:32 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"00D210000000OEp!AQMAQL0Lafrcf7TQw6GP2Pu9oFBE6FfkLSSH58is.3gixmlZoAJiWexF4.xoQvzDx41w4PX8dynXndNjoEo0tBB6BNA6LhU8","instance_url":"https://sfhousing--full.cs26.my.salesforce.com","id":"https://test.salesforce.com/id/00D210000000OEpEAM/00521000000E79dAAC","token_type":"Bearer","issued_at":"1469667635474","signature":"Eml4OcEQVDskV4V4qTK+vawzee4XArprjwN4Xj5Iizw="}'
    http_version:
  recorded_at: Thu, 28 Jul 2016 01:00:35 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs26.my.salesforce.com/services/apexrest/shortForm/list/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth 00D210000000OEp!AQMAQL0Lafrcf7TQw6GP2Pu9oFBE6FfkLSSH58is.3gixmlZoAJiWexF4.xoQvzDx41w4PX8dynXndNjoEo0tBB6BNA6LhU8
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Thu, 28 Jul 2016 01:00:36 GMT
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; font-src https:
        data:; report-uri /_/ContentDomainCSPNoAuth?type=mydomain'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=0wQJh0M8RGWgedx0BFma9w;Path=/;Domain=.salesforce.com;Expires=Mon,
        26-Sep-2016 01:00:36 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Thu, 28 Jul 2016 01:00:38 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs26.my.salesforce.com/services/apexrest/ListingDetails
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth 00D210000000OEp!AQMAQL0Lafrcf7TQw6GP2Pu9oFBE6FfkLSSH58is.3gixmlZoAJiWexF4.xoQvzDx41w4PX8dynXndNjoEo0tBB6BNA6LhU8
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 28 Jul 2016 01:00:38 GMT
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; font-src https:
        data:; report-uri /_/ContentDomainCSPNoAuth?type=mydomain'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=BV1UrYmJRhOrqZc_Wp5K9A;Path=/;Domain=.salesforce.com;Expires=Mon,
        26-Sep-2016 01:00:38 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Thu, 28 Jul 2016 01:00:40 GMT
recorded_with: VCR 3.0.3
