---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jul 2018 22:58:36 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=DxZeCUT8QFChKYe-DdAzrg;Path=/;Domain=.salesforce.com;Expires=Sat,
        08-Sep-2018 22:58:36 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs97.my.salesforce.com","id":"https://test.salesforce.com/id/00D0U0000000Qf1UAE/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1531263516519","signature":"RlzyxmJpQAUuJhq6qay59rVHABdbS1yViBcaidx4Xjs="}'
    http_version: 
  recorded_at: Tue, 10 Jul 2018 22:58:38 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs97.my.salesforce.com/services/apexrest/shortForm/list/0030P00001y3eLHQAY
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jul 2018 22:58:36 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0U0000000Qf1m";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D0U0000000Qf1m";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=xjF49CIbQl-cZfZqscSzQQ;Path=/;Domain=.salesforce.com;Expires=Sat,
        08-Sep-2018 22:58:36 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '[{"whichOne":null,"totalMonthlyRent":null,"status":"Draft","shortFormPreferences":[],"referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":"1","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":"Home","phone":"2222222222","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Dolendo","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","contactId":"0030P00001y3eLHQAY","city":null,"candidateScore":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AwpInQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},"other":null,"name":"APP-00038758","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038758","listingID":"a0WU000000ClNXGMA3","id":"a0o0P00000FEUwHQAX","householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":"Spouse","race":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Kanobi","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","contactId":null,"city":null,"candidateScore":null,"appMemberType":"Household
        Member","appMemberId":"a0n0U000008ZR6LQAW","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null}],"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":null,"externalSessionId":"","didApplicantUseHousingCounselingAgency":"No","appRTType":"Rental_Short_Form","applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false,"adaPrioritiesSelected":null}]'
    http_version: 
  recorded_at: Tue, 10 Jul 2018 22:58:38 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs97.my.salesforce.com/services/apexrest/ListingDetails?ids=a0WU000000ClNXGMA3
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jul 2018 22:58:37 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0U0000000Qf1m";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D0U0000000Qf1m";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=phm4wEI7Tc2T8zOCbliMaw;Path=/;Domain=.salesforce.com;Expires=Sat,
        08-Sep-2018 22:58:37 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        W3sidW5pdFN1bW1hcmllcyI6eyJyZXNlcnZlZCI6bnVsbCwiZ2VuZXJhbCI6
        W3sidW5pdFR5cGUiOiJTdHVkaW8iLCJ0b3RhbFVuaXRzIjoxLCJwcmlvcml0
        aWVzIjpudWxsLCJtaW5TcXVhcmVGdCI6NDc2LCJtaW5SZW50YWxNaW5JbmNv
        bWUiOjI0NzcuNTAsIm1pblBlcmNlbnRJbmNvbWUiOm51bGwsIm1pbk9jY3Vw
        YW5jeSI6MSwibWluTW9udGhseVJlbnQiOjk5MS4wMCwibWF4U3F1YXJlRnQi
        OjQ3NiwibWF4UmVudGFsTWluSW5jb21lIjoyNDc3LjUwLCJtYXhQZXJjZW50
        SW5jb21lIjpudWxsLCJtYXhPY2N1cGFuY3kiOjIsIm1heE1vbnRobHlSZW50
        Ijo5OTEuMDAsImxpc3RpbmdJRCI6ImEwV1UwMDAwMDBDbE5YR01BMyJ9XX0s
        InJlc2VydmVkRGVzY3JpcHRvciI6bnVsbCwicHJpb3JpdGllc0Rlc2NyaXB0
        b3IiOm51bGwsImxpc3RpbmdJRCI6ImEwV1UwMDAwMDBDbE5YR01BMyIsImxp
        c3RpbmciOnsiYXR0cmlidXRlcyI6eyJ0eXBlIjoiTGlzdGluZ19fYyIsInVy
        bCI6Ii9zZXJ2aWNlcy9kYXRhL3YzNS4wL3NvYmplY3RzL0xpc3RpbmdfX2Mv
        YTBXVTAwMDAwMENsTlhHTUEzIn0sIk5hbWUiOiI4IFRlbnRoIChORU1BKSBV
        bml0IDc0MiIsIkluX0xvdHRlcnlfX2MiOjMsIlVuaXRzX0F2YWlsYWJsZV9f
        YyI6MCwiU0FTRV9SZXF1aXJlZF9mb3JfTG90dGVyeV9UaWNrZXRfX2MiOmZh
        bHNlLCJuR2VuZXJhbF9BcHBsaWNhdGlvbl9Ub3RhbF9fYyI6NCwiQnVpbGRp
        bmdfTmFtZV9fYyI6Ik5FTUEiLCJQcm9qZWN0X0lEX19jIjoiMjAwNy0wMTEi
        LCJCdWlsZGluZ19TdHJlZXRfQWRkcmVzc19fYyI6IjggVGVudGggU3RyZWV0
        IiwiQnVpbGRpbmdfQ2l0eV9fYyI6IlNhbiBGcmFuY2lzY28iLCJCdWlsZGlu
        Z19TdGF0ZV9fYyI6IkNBIiwiQnVpbGRpbmdfWmlwX0NvZGVfX2MiOiI5NDEw
        MyIsIkRldmVsb3Blcl9fYyI6IlRlbnRoICYgTWFya2V0IExMQyIsIk5laWdo
        Ym9yaG9vZF9fYyI6IlNvdXRoIG9mIE1hcmtldCIsIlllYXJfQnVpbHRfX2Mi
        OjIwMTMsIkxhc3RNb2RpZmllZERhdGUiOiIyMDE4LTA3LTEwVDIyOjU2OjE3
        LjAwMCswMDAwIiwiTWFya2V0aW5nX1VSTF9fYyI6IjgtVGVudGgtKE5FTUEp
        LSIsIkJ1aWxkaW5nX1VSTF9fYyI6Imh0dHA6Ly9zZm1vaGNkLm9yZy9zaXRl
        cy9kZWZhdWx0L2ZpbGVzL0RvY3VtZW50cy9NT0gvSG91c2luZyUyMExpc3Rp
        bmclMjBQaG90b3MvTkVNQTgtMTB0aFN0LmpwZyIsIkxlZ2FsX0Rpc2NsYWlt
        ZXJzX19jIjoiQWxsIEJNUiByZW50ZXJzIG11c3QgcmV2aWV3IGFuZCBhY2tu
        b3dsZWRnZSB0aGUgPGEgaHJlZj1cImh0dHA6Ly9zZm1vaGNkLm9yZy9kb2N1
        bWVudHMtZ292ZXJuaW5nLWFuZC1leHBsYWluaW5nLWluY2x1c2lvbmFyeS1o
        b3VzaW5nLXByb2dyYW1cIiB0YXJnZXQ9XCJfYmxhbmtcIj5JbmNsdXNpb25h
        cnkgQWZmb3JkYWJsZSBIb3VzaW5nIFByb2dyYW0gTW9uaXRvcmluZyBhbmQg
        UHJvY2VkdXJlcyBNYW51YWwgMjAxMzwvYT4gdGhhdCBnb3Zlcm5zIHRoaXMg
        cHJvcGVydHkgdXBvbiB0aGUgc2lnbmluZyBvZiBhIGxlYXNlIGZvciBhIEJN
        UiB1bml0Ljxicj48YnI+QXBwbGljYW50cyBzaG91bGQgYmUgaW5mb3JtZWQg
        dGhhdCBCTVIgcmVudGFsIHVuaXRzIGluIHNvbWUgYnVpbGRpbmdzIG1heSBj
        b252ZXJ0IHRvIG93bmVyc2hpcCB1bml0cyBpbiB0aGUgZnV0dXJlLsKgIElu
        IHRoZSBjYXNlIG9mIGNvbnZlcnNpb24sIEJNUiByZW50ZXJzIHdpbGwgYmUg
        YWZmb3JkZWQgY2VydGFpbiByaWdodHMgYXMgZXhwbGFpbmVkIGluIHRoZSA8
        YSBocmVmPVwiaHR0cDovL3NmbW9oY2Qub3JnL2RvY3VtZW50cy1nb3Zlcm5p
        bmctYW5kLWV4cGxhaW5pbmctaW5jbHVzaW9uYXJ5LWhvdXNpbmctcHJvZ3Jh
        bVwiIHRhcmdldD1cIl9ibGFua1wiPkluY2x1c2lvbmFyeSBBZmZvcmRhYmxl
        IEhvdXNpbmcgUHJvZ3JhbSBNb25pdG9yaW5nIGFuZCBQcm9jZWR1cmVzIE1h
        bnVhbCAyMDEzPC9hPi4gQXBwbGljYW50cyBzaG91bGQgaW5xdWlyZSB3aXRo
        IHRoZSBidWlsZGluZyBjb250YWN0IHBlcnNvbiBsaXN0ZWQgYWJvdmUgdG8g
        ZGV0ZXJtaW5lIGlmIHRoZSBidWlsZGluZyBoYXMgYSBtaW5pbXVtIG51bWJl
        ciBvZiB5ZWFycyB0aGF0IGl0IG11c3QgcmVtYWluIGEgcmVudGFsIGJ1aWxk
        aW5nLsKgIChTb21lIGJ1aWxkaW5ncyBtYXkgaGF2ZSBzdWNoIHJlc3RyaWN0
        aW9ucyBiYXNlZCBvbiBnb3Zlcm5tZW50IHNvdXJjZXMgb2YgZmluYW5jaW5n
        IGZvciB0aGVpciBidWlsZGluZy4pIE1vc3QgYnVpbGRpbmdzIG1heSBoYXZl
        IG5vIHJlc3RyaWN0aW9ucyBvbiBjb252ZXJzaW9uIGF0IGFsbC48YnI+PGJy
        Pkl0IGlzIGFsc28gaW1wb3J0YW50IHRvIG5vdGUgdGhhdCB1bml0cyBnb3Zl
        cm5lZCBieSB0aGUgSW5jbHVzaW9uYXJ5IEhvdXNpbmcgUHJvZ3JhbSBhcmUg
        Tk9UIGdvdmVybmVkIGJ5IHRoZSBTYW4gRnJhbmNpc2NvIFJlbnQgT3JkaW5h
        bmNlIChhbHNvIGtub3duIGFzIOKAnHJlbnQgY29udHJvbOKAnSkuIEFtb25n
        IG90aGVyIHJ1bGVzLCByZW50cyBtYXkgaW5jcmVhc2UgYmV5b25kIGluY3Jl
        YXNlcyBhbGxvd2VkIHVuZGVyIOKAnHJlbnQgY29udHJvbC7igJ3CoCBQbGVh
        c2Ugc2VlIHRoZSA8YSBocmVmPVwiaHR0cDovL3NmbW9oY2Qub3JnL2RvY3Vt
        ZW50cy1nb3Zlcm5pbmctYW5kLWV4cGxhaW5pbmctaW5jbHVzaW9uYXJ5LWhv
        dXNpbmctcHJvZ3JhbVwiIHRhcmdldD1cIl9ibGFua1wiPkluY2x1c2lvbmFy
        eSBBZmZvcmRhYmxlIEhvdXNpbmcgUHJvZ3JhbSBNb25pdG9yaW5nIGFuZCBQ
        cm9jZWR1cmVzIE1hbnVhbCAyMDEzPC9hPiBmb3IgbW9yZSBpbmZvcm1hdGlv
        bi4iLCJBcHBsaWNhdGlvbl9Pcmdhbml6YXRpb25fX2MiOiJDYXJpdGFzIE1n
        bXQgQ29ycCIsIkFwcGxpY2F0aW9uX1N0cmVldF9BZGRyZXNzX19jIjoiMTM1
        OCBWYWxlbmNpYSBTdC4iLCJBcHBsaWNhdGlvbl9DaXR5X19jIjoiU2FuIEZy
        YW5jaXNjbyIsIkFwcGxpY2F0aW9uX1N0YXRlX19jIjoiQ0EiLCJBcHBsaWNh
        dGlvbl9Qb3N0YWxfQ29kZV9fYyI6Ijk0MTEwIiwiQXBwbGljYXRpb25fUGhv
        bmVfX2MiOiIoNDE1KSA2NDctNzE5MSBleHQuMTEyIiwiTG90dGVyeV9SZXN1
        bHRzX0RhdGVfX2MiOiIyMDE2LTA2LTEwIiwiTG90dGVyeV9WZW51ZV9fYyI6
        Ik1heW9yJ3MgT2ZmaWNlIG9mIEhvdXNpbmcgYW5kIENvbW11bml0eSBEZXZl
        bG9wbWVudCIsIkxvdHRlcnlfU3RyZWV0X0FkZHJlc3NfX2MiOiIxIFNvdXRo
        IFZhbiBOZXNzIEF2ZS4sIDV0aCBGbG9vciIsIkxvdHRlcnlfQ2l0eV9fYyI6
        IlNhbiBGcmFuY2lzY28iLCJMb3R0ZXJ5X0RhdGVfX2MiOiIyMDE2LTA2LTA4
        VDE4OjAwOjAwLjAwMCswMDAwIiwiTG90dGVyeV9SZXN1bHRzX19jIjpmYWxz
        ZSwiQWNjZXB0aW5nX09ubGluZV9BcHBsaWNhdGlvbnNfX2MiOmZhbHNlLCJM
        b3R0ZXJ5X1dpbm5lcnNfX2MiOjIwLCJBTUlfUGVyY2VudGFnZV9fYyI6NTUu
        MDAsIkNyZWRpdF9SYXRpbmdfX2MiOiJNdXN0IGhhdmUgYSBjcmVkaXQgc2Nv
        cmUgb2YgNjAwIG9yIGhpZ2hlciB0byBsZWFzZSB3aXRob3V0IGEgZ3VhcmFu
        dG9yLiBDb21wbGV0ZSBhIHJlc2lkZW50IHZlcmlmaWNhdGlvbiBmb3JtLiBB
        cHBsaWNhbnQgd2l0aCBubyBldmljdGlvbiB3aXRoaW4gdGhlIHBhc3QgNyB5
        ZWFycyBvZiB0aGVpciByZW50YWwgaGlzdG9yeS4iLCJDcmltaW5hbF9IaXN0
        b3J5X19jIjoiTm8gZmVsb25pZXMgd2l0aGluIHRoZSBwYXN0IDcgeWVhcnMu
        IENvbXBsZXRlIGJhY2tncm91bmQgY2hlY2sgZm9ybS4gUXVhbGlmaWVkIGFw
        cGxpY2FudHMgd2l0aCBjcmltaW5hbCBoaXN0b3J5IHdpbGwgYmUgY29uc2lk
        ZXJlZCBmb3IgaG91c2luZyBpbiBjb21wbGlhbmNlIHdpdGggQXJ0aWNsZSA0
        OSBvZiB0aGUgU2FuIEZyYW5jaXNjbyBQb2xpY2UgQ29kZSwg4oCcVGhlIEZh
        aXIgQ2hhbmNlIE9yZGluYW5jZS7igJ0iLCJFdmljdGlvbl9IaXN0b3J5X19j
        IjoiTm8gZXZpY3Rpb24gd2l0aGluIHRoZSBwYXN0IDcgeWVhcnMgb2YgYXBw
        bGljYW50J3MgcmVudGFsIGhpc3RvcnkuIiwiTGVhc2luZ19BZ2VudF9OYW1l
        X19jIjoiQnJpYW4gTWluYWxsIiwiTGVhc2luZ19BZ2VudF9FbWFpbF9fYyI6
        ImJyaWFuLm1pbmFsbEBjYXJpdGFzbWFuYWdlbWVudC5jb20iLCJMZWFzaW5n
        X0FnZW50X1Bob25lX19jIjoiKDQxNSkgNjQ3LTcxOTEgeDEyNyIsIkxlYXNp
        bmdfQWdlbnRfU3RhdGVfX2MiOiJDYWxpZm9ybmlhIiwiRG93bmxvYWRfVVJM
        X19jIjoiaHR0cDovL3NmbW9oY2Qub3JnL2Jtci1yZW50YWwtYXBwbGljYXRp
        b24iLCJBY2NlcHRpbmdfYXBwbGljYXRpb25zX2F0X2xlYXNpbmdfYWdlbnRf
        X2MiOmZhbHNlLCJBY2NlcHRpbmdfYXBwbGljYXRpb25zX2J5X1BPX0JveF9f
        YyI6ZmFsc2UsIkJsYW5rX3BhcGVyX2FwcGxpY2F0aW9uX2Nhbl9iZV9waWNr
        ZWRfdXBfX2MiOmZhbHNlLCJGZWVfX2MiOjQ0LjAwLCJEZXBvc2l0X01pbl9f
        YyI6OTkxLjAwLCJEZXBvc2l0X01heF9fYyI6OTkxLjAwLCJDb3N0c19Ob3Rf
        SW5jbHVkZWRfX2MiOiJSZXBsYWNlbWVudCBmb2JzL3JlbW90ZXMgYXJlICQ1
        MCBlYWNoLiBcclxuTGF0ZSByZW50IHBheW1lbnQgZmVlIGlzICQ1MCwgdW5w
        YWlkIGJhbGFuY2UgYWZ0ZXIgNXRoIG9mIHRoZSBtb250aC4iLCJCdWlsZGlu
        Z19TZWxlY3Rpb25fQ3JpdGVyaWFfX2MiOiJodHRwOi8vc2Ztb2hjZC5vcmcv
        c2l0ZXMvZGVmYXVsdC9maWxlcy9Eb2N1bWVudHMvTU9IL05FTUElMjBCTVIl
        MjBSZXNpZGVudCUyMFNlbGVjdGlvbiUyMENyaXRlcmlhLnBkZiIsIlJlcXVp
        cmVkX0RvY3VtZW50c19fYyI6IkZ1bGwgZG9jdW1lbnRhdGlvbiByZXF1aXJl
        ZCBpZiBhcHBsaWNhbnQgaXMgc2VsZWN0ZWQgaW4gbGlzdGluZyBsb3R0ZXJ5
        LiIsIlNtb2tpbmdfUG9saWN5X19jIjoiTm9uZSBzdGF0ZWQiLCJQZXRfUG9s
        aWN5X19jIjoiUGV0IGRlcG9zaXQ6ICQ1MDAgcGVyIHBldCBhbmQgJDc1L21v
        bnRoIHBldCBmZWUgcGVyIHBldCkiLCJSZXNlcnZlZF9jb21tdW5pdHlfbWF4
        aW11bV9hZ2VfX2MiOjAsIlJlc2VydmVkX2NvbW11bml0eV9taW5pbXVtX2Fn
        ZV9fYyI6MCwiaGFzV2FpdGxpc3RfX2MiOmZhbHNlLCJUb3RhbF93YWl0bGlz
        dF9vcGVuaW5nc19fYyI6MCwiVG90YWxfbnVtYmVyX29mX2J1aWxkaW5nX3Vu
        aXRzX19jIjo4LCJJZCI6ImEwV1UwMDAwMDBDbE5YR01BMyIsIk9wZW5fSG91
        c2VzX19yIjp7InRvdGFsU2l6ZSI6MSwiZG9uZSI6dHJ1ZSwicmVjb3JkcyI6
        W3siYXR0cmlidXRlcyI6eyJ0eXBlIjoiT3Blbl9Ib3VzZXNfX2MiLCJ1cmwi
        OiIvc2VydmljZXMvZGF0YS92MzUuMC9zb2JqZWN0cy9PcGVuX0hvdXNlc19f
        Yy9hMFlVMDAwMDAwQ29OS0FNQTMifSwiTGlzdGluZ19fYyI6ImEwV1UwMDAw
        MDBDbE5YR01BMyIsIklkIjoiYTBZVTAwMDAwMENvTktBTUEzIiwiRGF0ZV9f
        YyI6IjIwMTYtMDUtMjYiLCJTdGFydF9UaW1lX19jIjoiNDowMCBQTSIsIkVu
        ZF9UaW1lX19jIjoiNjowMCBQTSJ9XX0sIlVuaXRzX19yIjp7InRvdGFsU2l6
        ZSI6MSwiZG9uZSI6dHJ1ZSwicmVjb3JkcyI6W3siYXR0cmlidXRlcyI6eyJ0
        eXBlIjoiVW5pdF9fYyIsInVybCI6Ii9zZXJ2aWNlcy9kYXRhL3YzNS4wL3Nv
        YmplY3RzL1VuaXRfX2MvYTBiVTAwMDAwMUMwY0luSUFKIn0sIkxpc3Rpbmdf
        X2MiOiJhMFdVMDAwMDAwQ2xOWEdNQTMiLCJJZCI6ImEwYlUwMDAwMDFDMGNJ
        bklBSiIsIlVuaXRfVHlwZV9fYyI6IlN0dWRpbyIsIkJNUl9SZW50X01vbnRo
        bHlfX2MiOjk5MS4wMCwiQk1SX1JlbnRhbF9NaW5pbXVtX01vbnRobHlfSW5j
        b21lX05lZWRlZF9fYyI6MjQ3Ny41MCwiaXNSZXNlcnZlZENvbW11bml0eV9f
        YyI6ZmFsc2UsIkFNSV9jaGFydF90eXBlX19jIjoiSFVEIFVuYWRqdXN0ZWQi
        LCJBTUlfY2hhcnRfeWVhcl9fYyI6MjAxNiwib2ZfQU1JX2Zvcl9QcmljaW5n
        X1VuaXRfX2MiOjU1fV19fSwiZG9lc01hdGNoIjpudWxsLCJjaGFydFR5cGVz
        IjpbeyJ5ZWFyIjoyMDE2LCJwZXJjZW50Ijo1NSwibnVtT2ZIb3VzZWhvbGQi
        Om51bGwsImNoYXJ0VHlwZSI6IkhVRCBVbmFkanVzdGVkIiwiYW1vdW50Ijpu
        dWxsfV19XQ==
    http_version: 
  recorded_at: Tue, 10 Jul 2018 22:58:39 GMT
recorded_with: VCR 3.0.3
