---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 04 Apr 2018 17:42:00 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=d8ITOXeiTPq0FFF653_rIg;Path=/;Domain=.salesforce.com;Expires=Sun,
        03-Jun-2018 17:42:00 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs95.my.salesforce.com","id":"https://test.salesforce.com/id/00D0x000000CtkoEAC/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1522863721520","signature":"bL6o/f4fHP21oG2mjuvRalc+5yCiYDz4ayaL5wLN9JM="}'
    http_version: 
  recorded_at: Wed, 04 Apr 2018 17:42:01 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs95.my.salesforce.com/services/apexrest/shortForm/list/0030P00001y3eLHQAY
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 04 Apr 2018 17:42:02 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0x000000Ctkop";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D0x000000Ctkop";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=kYPp9S1FQw-Bt15N8CKbHw;Path=/;Domain=.salesforce.com;Expires=Sun,
        03-Jun-2018 17:42:02 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '[{"totalMonthlyRent":null,"status":"Submitted","shortFormPreferences":[],"referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":"1","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":"Home","phone":"2222222222","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Dolendo","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","contactId":"0030P00001y3eLHQAY","city":null,"candidateScore":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AwpInQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},"name":"APP-00038758","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038758","listingID":"a0WU000000ClNXGMA3","id":"a0o0P00000FEUwHQAX","householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":"Spouse","race":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Kanobi","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","contactId":null,"city":null,"candidateScore":null,"appMemberType":"Household
        Member","appMemberId":"a0n0x000000RMPiAAO","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null}],"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":null,"externalSessionId":"","appRTType":"Rental_Short_Form","applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false,"adaPrioritiesSelected":null}]'
    http_version: 
  recorded_at: Wed, 04 Apr 2018 17:42:02 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs95.my.salesforce.com/services/apexrest/ListingDetails?ids=a0WU000000ClNXGMA3
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 04 Apr 2018 17:42:02 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0x000000Ctkop";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D0x000000Ctkop";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=iklv_uI8Te603zVjt2UYuA;Path=/;Domain=.salesforce.com;Expires=Sun,
        03-Jun-2018 17:42:02 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        W3sidW5pdFN1bW1hcmllcyI6eyJyZXNlcnZlZCI6bnVsbCwiZ2VuZXJhbCI6
        W3sidW5pdFR5cGUiOiJTdHVkaW8iLCJ0b3RhbFVuaXRzIjoxLCJwcmlvcml0
        aWVzIjpudWxsLCJtaW5TcXVhcmVGdCI6NDc2LCJtaW5SZW50YWxNaW5JbmNv
        bWUiOjI0NzcuNTAsIm1pblBlcmNlbnRJbmNvbWUiOm51bGwsIm1pbk9jY3Vw
        YW5jeSI6MSwibWluTW9udGhseVJlbnQiOjk5MS4wMCwibWF4U3F1YXJlRnQi
        OjQ3NiwibWF4UmVudGFsTWluSW5jb21lIjoyNDc3LjUwLCJtYXhQZXJjZW50
        SW5jb21lIjpudWxsLCJtYXhPY2N1cGFuY3kiOjIsIm1heE1vbnRobHlSZW50
        Ijo5OTEuMDAsImxpc3RpbmdJRCI6ImEwV1UwMDAwMDBDbE5YR01BMyJ9XX0s
        InJlc2VydmVkRGVzY3JpcHRvciI6bnVsbCwicHJpb3JpdGllc0Rlc2NyaXB0
        b3IiOm51bGwsImxpc3RpbmdJRCI6ImEwV1UwMDAwMDBDbE5YR01BMyIsImxp
        c3RpbmciOnsiYXR0cmlidXRlcyI6eyJ0eXBlIjoiTGlzdGluZ19fYyIsInVy
        bCI6Ii9zZXJ2aWNlcy9kYXRhL3YzNS4wL3NvYmplY3RzL0xpc3RpbmdfX2Mv
        YTBXVTAwMDAwMENsTlhHTUEzIn0sIk5hbWUiOiI4IFRlbnRoIChORU1BKSBV
        bml0IDc0MiIsIkluX0xvdHRlcnlfX2MiOjQsIlVuaXRzX0F2YWlsYWJsZV9f
        YyI6MCwiU0FTRV9SZXF1aXJlZF9mb3JfTG90dGVyeV9UaWNrZXRfX2MiOmZh
        bHNlLCJuR2VuZXJhbF9BcHBsaWNhdGlvbl9Ub3RhbF9fYyI6NCwiQnVpbGRp
        bmdfTmFtZV9fYyI6Ik5FTUEiLCJQcm9qZWN0X0lEX19jIjoiMjAwNy0wMTEi
        LCJCdWlsZGluZ19TdHJlZXRfQWRkcmVzc19fYyI6IjggVGVudGggU3RyZWV0
        IiwiQnVpbGRpbmdfQ2l0eV9fYyI6IlNhbiBGcmFuY2lzY28iLCJCdWlsZGlu
        Z19TdGF0ZV9fYyI6IkNBIiwiQnVpbGRpbmdfWmlwX0NvZGVfX2MiOiI5NDEw
        MyIsIkRldmVsb3Blcl9fYyI6IlRlbnRoICYgTWFya2V0IExMQyIsIk5laWdo
        Ym9yaG9vZF9fYyI6IlNvdXRoIG9mIE1hcmtldCIsIlllYXJfQnVpbHRfX2Mi
        OjIwMTMsIkxhc3RNb2RpZmllZERhdGUiOiIyMDE4LTA0LTA0VDE2OjU2OjQw
        LjAwMCswMDAwIiwiQnVpbGRpbmdfVVJMX19jIjoiaHR0cDovL3NmbW9oY2Qu
        b3JnL3NpdGVzL2RlZmF1bHQvZmlsZXMvRG9jdW1lbnRzL01PSC9Ib3VzaW5n
        JTIwTGlzdGluZyUyMFBob3Rvcy9ORU1BOC0xMHRoU3QuanBnIiwiTGVnYWxf
        RGlzY2xhaW1lcnNfX2MiOiJBbGwgQk1SIHJlbnRlcnMgbXVzdCByZXZpZXcg
        YW5kIGFja25vd2xlZGdlIHRoZSA8YSBocmVmPVwiaHR0cDovL3NmbW9oY2Qu
        b3JnL2RvY3VtZW50cy1nb3Zlcm5pbmctYW5kLWV4cGxhaW5pbmctaW5jbHVz
        aW9uYXJ5LWhvdXNpbmctcHJvZ3JhbVwiIHRhcmdldD1cIl9ibGFua1wiPklu
        Y2x1c2lvbmFyeSBBZmZvcmRhYmxlIEhvdXNpbmcgUHJvZ3JhbSBNb25pdG9y
        aW5nIGFuZCBQcm9jZWR1cmVzIE1hbnVhbCAyMDEzPC9hPiB0aGF0IGdvdmVy
        bnMgdGhpcyBwcm9wZXJ0eSB1cG9uIHRoZSBzaWduaW5nIG9mIGEgbGVhc2Ug
        Zm9yIGEgQk1SIHVuaXQuPGJyPjxicj5BcHBsaWNhbnRzIHNob3VsZCBiZSBp
        bmZvcm1lZCB0aGF0IEJNUiByZW50YWwgdW5pdHMgaW4gc29tZSBidWlsZGlu
        Z3MgbWF5IGNvbnZlcnQgdG8gb3duZXJzaGlwIHVuaXRzIGluIHRoZSBmdXR1
        cmUuwqAgSW4gdGhlIGNhc2Ugb2YgY29udmVyc2lvbiwgQk1SIHJlbnRlcnMg
        d2lsbCBiZSBhZmZvcmRlZCBjZXJ0YWluIHJpZ2h0cyBhcyBleHBsYWluZWQg
        aW4gdGhlIDxhIGhyZWY9XCJodHRwOi8vc2Ztb2hjZC5vcmcvZG9jdW1lbnRz
        LWdvdmVybmluZy1hbmQtZXhwbGFpbmluZy1pbmNsdXNpb25hcnktaG91c2lu
        Zy1wcm9ncmFtXCIgdGFyZ2V0PVwiX2JsYW5rXCI+SW5jbHVzaW9uYXJ5IEFm
        Zm9yZGFibGUgSG91c2luZyBQcm9ncmFtIE1vbml0b3JpbmcgYW5kIFByb2Nl
        ZHVyZXMgTWFudWFsIDIwMTM8L2E+LiBBcHBsaWNhbnRzIHNob3VsZCBpbnF1
        aXJlIHdpdGggdGhlIGJ1aWxkaW5nIGNvbnRhY3QgcGVyc29uIGxpc3RlZCBh
        Ym92ZSB0byBkZXRlcm1pbmUgaWYgdGhlIGJ1aWxkaW5nIGhhcyBhIG1pbmlt
        dW0gbnVtYmVyIG9mIHllYXJzIHRoYXQgaXQgbXVzdCByZW1haW4gYSByZW50
        YWwgYnVpbGRpbmcuwqAgKFNvbWUgYnVpbGRpbmdzIG1heSBoYXZlIHN1Y2gg
        cmVzdHJpY3Rpb25zIGJhc2VkIG9uIGdvdmVybm1lbnQgc291cmNlcyBvZiBm
        aW5hbmNpbmcgZm9yIHRoZWlyIGJ1aWxkaW5nLikgTW9zdCBidWlsZGluZ3Mg
        bWF5IGhhdmUgbm8gcmVzdHJpY3Rpb25zIG9uIGNvbnZlcnNpb24gYXQgYWxs
        Ljxicj48YnI+SXQgaXMgYWxzbyBpbXBvcnRhbnQgdG8gbm90ZSB0aGF0IHVu
        aXRzIGdvdmVybmVkIGJ5IHRoZSBJbmNsdXNpb25hcnkgSG91c2luZyBQcm9n
        cmFtIGFyZSBOT1QgZ292ZXJuZWQgYnkgdGhlIFNhbiBGcmFuY2lzY28gUmVu
        dCBPcmRpbmFuY2UgKGFsc28ga25vd24gYXMg4oCccmVudCBjb250cm9s4oCd
        KS4gQW1vbmcgb3RoZXIgcnVsZXMsIHJlbnRzIG1heSBpbmNyZWFzZSBiZXlv
        bmQgaW5jcmVhc2VzIGFsbG93ZWQgdW5kZXIg4oCccmVudCBjb250cm9sLuKA
        ncKgIFBsZWFzZSBzZWUgdGhlIDxhIGhyZWY9XCJodHRwOi8vc2Ztb2hjZC5v
        cmcvZG9jdW1lbnRzLWdvdmVybmluZy1hbmQtZXhwbGFpbmluZy1pbmNsdXNp
        b25hcnktaG91c2luZy1wcm9ncmFtXCIgdGFyZ2V0PVwiX2JsYW5rXCI+SW5j
        bHVzaW9uYXJ5IEFmZm9yZGFibGUgSG91c2luZyBQcm9ncmFtIE1vbml0b3Jp
        bmcgYW5kIFByb2NlZHVyZXMgTWFudWFsIDIwMTM8L2E+IGZvciBtb3JlIGlu
        Zm9ybWF0aW9uLiIsIkFwcGxpY2F0aW9uX09yZ2FuaXphdGlvbl9fYyI6IkNh
        cml0YXMgTWdtdCBDb3JwIiwiQXBwbGljYXRpb25fU3RyZWV0X0FkZHJlc3Nf
        X2MiOiIxMzU4IFZhbGVuY2lhIFN0LiIsIkFwcGxpY2F0aW9uX0NpdHlfX2Mi
        OiJTYW4gRnJhbmNpc2NvIiwiQXBwbGljYXRpb25fU3RhdGVfX2MiOiJDQSIs
        IkFwcGxpY2F0aW9uX1Bvc3RhbF9Db2RlX19jIjoiOTQxMTAiLCJBcHBsaWNh
        dGlvbl9QaG9uZV9fYyI6Iig0MTUpIDY0Ny03MTkxIGV4dC4xMTIiLCJMb3R0
        ZXJ5X1Jlc3VsdHNfRGF0ZV9fYyI6IjIwMTYtMDYtMTAiLCJMb3R0ZXJ5X1N0
        YXJ0X1RpbWVfX2MiOiIxMTowMCBBTSIsIkxvdHRlcnlfVmVudWVfX2MiOiJN
        YXlvcidzIE9mZmljZSBvZiBIb3VzaW5nIGFuZCBDb21tdW5pdHkgRGV2ZWxv
        cG1lbnQiLCJMb3R0ZXJ5X1N0cmVldF9BZGRyZXNzX19jIjoiMSBTb3V0aCBW
        YW4gTmVzcyBBdmUuLCA1dGggRmxvb3IiLCJMb3R0ZXJ5X0NpdHlfX2MiOiJT
        YW4gRnJhbmNpc2NvIiwiTG90dGVyeV9EYXRlX19jIjoiMjAxNi0wNi0wOFQx
        ODowMDowMC4wMDArMDAwMCIsIkxvdHRlcnlfUmVzdWx0c19fYyI6ZmFsc2Us
        IkFjY2VwdGluZ19PbmxpbmVfQXBwbGljYXRpb25zX19jIjpmYWxzZSwiTG90
        dGVyeV9XaW5uZXJzX19jIjoyMCwiQU1JX1BlcmNlbnRhZ2VfX2MiOjU1LjAw
        LCJDcmVkaXRfUmF0aW5nX19jIjoiTXVzdCBoYXZlIGEgY3JlZGl0IHNjb3Jl
        IG9mIDYwMCBvciBoaWdoZXIgdG8gbGVhc2Ugd2l0aG91dCBhIGd1YXJhbnRv
        ci4gQ29tcGxldGUgYSByZXNpZGVudCB2ZXJpZmljYXRpb24gZm9ybS4gQXBw
        bGljYW50IHdpdGggbm8gZXZpY3Rpb24gd2l0aGluIHRoZSBwYXN0IDcgeWVh
        cnMgb2YgdGhlaXIgcmVudGFsIGhpc3RvcnkuIiwiQ3JpbWluYWxfSGlzdG9y
        eV9fYyI6Ik5vIGZlbG9uaWVzIHdpdGhpbiB0aGUgcGFzdCA3IHllYXJzLiBD
        b21wbGV0ZSBiYWNrZ3JvdW5kIGNoZWNrIGZvcm0uIFF1YWxpZmllZCBhcHBs
        aWNhbnRzIHdpdGggY3JpbWluYWwgaGlzdG9yeSB3aWxsIGJlIGNvbnNpZGVy
        ZWQgZm9yIGhvdXNpbmcgaW4gY29tcGxpYW5jZSB3aXRoIEFydGljbGUgNDkg
        b2YgdGhlIFNhbiBGcmFuY2lzY28gUG9saWNlIENvZGUsIOKAnFRoZSBGYWly
        IENoYW5jZSBPcmRpbmFuY2Uu4oCdIiwiRXZpY3Rpb25fSGlzdG9yeV9fYyI6
        Ik5vIGV2aWN0aW9uIHdpdGhpbiB0aGUgcGFzdCA3IHllYXJzIG9mIGFwcGxp
        Y2FudCdzIHJlbnRhbCBoaXN0b3J5LiIsIkxlYXNpbmdfQWdlbnRfTmFtZV9f
        YyI6IkJyaWFuIE1pbmFsbCIsIkxlYXNpbmdfQWdlbnRfRW1haWxfX2MiOiJi
        cmlhbi5taW5hbGxAY2FyaXRhc21hbmFnZW1lbnQuY29tIiwiTGVhc2luZ19B
        Z2VudF9QaG9uZV9fYyI6Iig0MTUpIDY0Ny03MTkxIHgxMjciLCJMZWFzaW5n
        X0FnZW50X1N0YXRlX19jIjoiQ2FsaWZvcm5pYSIsIk9mZmljZV9PcGVuX19j
        IjoiOTowMCBBTSIsIk9mZmljZV9DbG9zZWRfX2MiOiI1OjAwIFBNIiwiRG93
        bmxvYWRfVVJMX19jIjoiaHR0cDovL3NmbW9oY2Qub3JnL2Jtci1yZW50YWwt
        YXBwbGljYXRpb24iLCJBY2NlcHRpbmdfYXBwbGljYXRpb25zX2F0X2xlYXNp
        bmdfYWdlbnRfX2MiOmZhbHNlLCJBY2NlcHRpbmdfYXBwbGljYXRpb25zX2J5
        X1BPX0JveF9fYyI6ZmFsc2UsIkJsYW5rX3BhcGVyX2FwcGxpY2F0aW9uX2Nh
        bl9iZV9waWNrZWRfdXBfX2MiOmZhbHNlLCJGZWVfX2MiOjQ0LjAwLCJEZXBv
        c2l0X01pbl9fYyI6OTkxLjAwLCJEZXBvc2l0X01heF9fYyI6OTkxLjAwLCJD
        b3N0c19Ob3RfSW5jbHVkZWRfX2MiOiJSZXBsYWNlbWVudCBmb2JzL3JlbW90
        ZXMgYXJlICQ1MCBlYWNoLiBcclxuTGF0ZSByZW50IHBheW1lbnQgZmVlIGlz
        ICQ1MCwgdW5wYWlkIGJhbGFuY2UgYWZ0ZXIgNXRoIG9mIHRoZSBtb250aC4i
        LCJCdWlsZGluZ19TZWxlY3Rpb25fQ3JpdGVyaWFfX2MiOiJodHRwOi8vc2Zt
        b2hjZC5vcmcvc2l0ZXMvZGVmYXVsdC9maWxlcy9Eb2N1bWVudHMvTU9IL05F
        TUElMjBCTVIlMjBSZXNpZGVudCUyMFNlbGVjdGlvbiUyMENyaXRlcmlhLnBk
        ZiIsIlJlcXVpcmVkX0RvY3VtZW50c19fYyI6IkZ1bGwgZG9jdW1lbnRhdGlv
        biByZXF1aXJlZCBpZiBhcHBsaWNhbnQgaXMgc2VsZWN0ZWQgaW4gbGlzdGlu
        ZyBsb3R0ZXJ5LiIsIlNtb2tpbmdfUG9saWN5X19jIjoiTm9uZSBzdGF0ZWQi
        LCJQZXRfUG9saWN5X19jIjoiUGV0IGRlcG9zaXQ6ICQ1MDAgcGVyIHBldCBh
        bmQgJDc1L21vbnRoIHBldCBmZWUgcGVyIHBldCkiLCJSZXNlcnZlZF9jb21t
        dW5pdHlfbWF4aW11bV9hZ2VfX2MiOjAsIlJlc2VydmVkX2NvbW11bml0eV9t
        aW5pbXVtX2FnZV9fYyI6MCwiaGFzV2FpdGxpc3RfX2MiOmZhbHNlLCJUb3Rh
        bF93YWl0bGlzdF9vcGVuaW5nc19fYyI6MCwiVG90YWxfbnVtYmVyX29mX2J1
        aWxkaW5nX3VuaXRzX19jIjo3LCJJZCI6ImEwV1UwMDAwMDBDbE5YR01BMyIs
        Ik9wZW5fSG91c2VzX19yIjp7InRvdGFsU2l6ZSI6MSwiZG9uZSI6dHJ1ZSwi
        cmVjb3JkcyI6W3siYXR0cmlidXRlcyI6eyJ0eXBlIjoiT3Blbl9Ib3VzZXNf
        X2MiLCJ1cmwiOiIvc2VydmljZXMvZGF0YS92MzUuMC9zb2JqZWN0cy9PcGVu
        X0hvdXNlc19fYy9hMFlVMDAwMDAwQ29OS0FNQTMifSwiTGlzdGluZ19fYyI6
        ImEwV1UwMDAwMDBDbE5YR01BMyIsIklkIjoiYTBZVTAwMDAwMENvTktBTUEz
        IiwiRGF0ZV9fYyI6IjIwMTYtMDUtMjYiLCJTdGFydF9UaW1lX19jIjoiNDow
        MCBQTSIsIkVuZF9UaW1lX19jIjoiNjowMCBQTSJ9XX0sIlVuaXRzX19yIjp7
        InRvdGFsU2l6ZSI6MSwiZG9uZSI6dHJ1ZSwicmVjb3JkcyI6W3siYXR0cmli
        dXRlcyI6eyJ0eXBlIjoiVW5pdF9fYyIsInVybCI6Ii9zZXJ2aWNlcy9kYXRh
        L3YzNS4wL3NvYmplY3RzL1VuaXRfX2MvYTBiVTAwMDAwMUMwY0luSUFKIn0s
        Ikxpc3RpbmdfX2MiOiJhMFdVMDAwMDAwQ2xOWEdNQTMiLCJJZCI6ImEwYlUw
        MDAwMDFDMGNJbklBSiIsIlVuaXRfVHlwZV9fYyI6IlN0dWRpbyIsIkJNUl9S
        ZW50X01vbnRobHlfX2MiOjk5MS4wMCwiQk1SX1JlbnRhbF9NaW5pbXVtX01v
        bnRobHlfSW5jb21lX05lZWRlZF9fYyI6MjQ3Ny41MCwiaXNSZXNlcnZlZENv
        bW11bml0eV9fYyI6ZmFsc2UsIkFNSV9jaGFydF90eXBlX19jIjoiSFVEIFVu
        YWRqdXN0ZWQiLCJBTUlfY2hhcnRfeWVhcl9fYyI6MjAxNiwib2ZfQU1JX2Zv
        cl9QcmljaW5nX1VuaXRfX2MiOjU1fV19fSwiZG9lc01hdGNoIjpudWxsLCJj
        aGFydFR5cGVzIjpbeyJ5ZWFyIjoyMDE2LCJwZXJjZW50Ijo1NSwibnVtT2ZI
        b3VzZWhvbGQiOm51bGwsImNoYXJ0VHlwZSI6IkhVRCBVbmFkanVzdGVkIiwi
        YW1vdW50IjpudWxsfV19XQ==
    http_version: 
  recorded_at: Wed, 04 Apr 2018 17:42:02 GMT
recorded_with: VCR 3.0.3
