---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 03 Aug 2017 22:35:10 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - referrer origin-when-cross-origin; upgrade-insecure-requests
      Set-Cookie:
      - BrowserId=DJpr_d7dTTG4cPjU8at7uA;Path=/;Domain=.salesforce.com;Expires=Mon,
        02-Oct-2017 22:35:11 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      - no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs25.my.salesforce.com","id":"https://test.salesforce.com/id/00D1b0000000hVgEAI/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1501799711273","signature":"fM43HSGAOR3UabetBLyLa/0DK1OT7tZTM3N3sBT4qGI="}'
    http_version: 
  recorded_at: Thu, 03 Aug 2017 22:35:11 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs25.my.salesforce.com/services/apexrest/shortForm/a0o1b0000001QZB
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 03 Aug 2017 22:35:11 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; max-age=86400;
        report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D1b0000000hVg";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Set-Cookie:
      - BrowserId=Bme2mJ2RTvKY4HZA0_6OtA;Path=/;Domain=.salesforce.com;Expires=Mon,
        02-Oct-2017 22:35:11 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"worksInSfPreferenceID":null,"workInSfPreferenceProof":null,"workInSfPreferenceNatKey":null,"status":"Submitted","referral":"Newspaper","primaryApplicant":{"zip":"94114-2535","yCoordinate":"4545683.89149254","xCoordinate":"-13629293.1192439","workInSf":"true","whichComponentOfLocatorWasUsed":"EAS","webAppID":"2","state":"CA","sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":null,"race":null,"phoneType":"Home","phone":"2222222222","noPhone":false,"noEmail":false,"noAddress":false,"neighborhoodPreferenceMatch":"Not
        Matched","middleName":null,"mailingZip":"94114-2535","mailingState":"CA","mailingCity":"SAN
        FRANCISCO","mailingAddress":"4053 18TH ST","lastName":"Doe","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Jane","ethnicity":null,"email":"li@uto.ke","DOB":"1990-02-22","contactId":"0031b000008vUDbAAM","city":"SAN
        FRANCISCO","candidateScore":100,"appMemberType":"Primary Applicant","appMemberId":"a0n1b000000QzN3AAK","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":"4053
        18TH ST"},"neighborhoodResidencePreferenceNatKey":null,"neighborhoodPreferenceProof":null,"neighborhoodPreferenceOptOut":false,"neighborhoodPreferenceID":null,"name":"APP-00092255","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00092255","liveWorkOptOut":false,"liveInSfPreferenceProof":null,"liveInSfPreferencePaper":false,"liveInSfPreferenceNatKey":null,"liveInSfPreferenceID":"a0n1b000000QzN3AAK","listingID":"a0W0P00000DZTkAUAX","id":"a0o1b0000001QZBAA2","householdVouchersSubsidies":"true","householdMembers":[],"formMetadata":"{\"completedSections\":{\"Intro\":true,\"You\":true,\"Household\":true,\"Preferences\":true,\"Income\":true},\"session_uid\":\"32cc44b0-83a0-44a9-b8a3-a2a8cfaee6af-bfcb1495-081e-448f-bc9c-7d5c9cd38754\"}","displacedPreferenceOptOut":false,"displacedPreferenceNatKey":null,"displacedPreferenceID":"a0n1b000000QzN3AAK","certOfPreferenceOptOut":false,"certOfPreferenceNatKey":null,"certOfPreferenceID":"a0n1b000000QzN3AAK","applicationSubmittedDate":"2017-08-03","applicationSubmissionType":"Electronic","applicationLanguage":"English","annualIncome":25000.00,"alternateContact":null,"agreeToTerms":true}'
    http_version: 
  recorded_at: Thu, 03 Aug 2017 22:35:12 GMT
- request:
    method: delete
    uri: https://sfhousing--full.cs25.my.salesforce.com/services/apexrest/shortForm/delete/a0o1b0000001QZB
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 03 Aug 2017 22:35:12 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; max-age=86400;
        report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D1b0000000hVg";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Set-Cookie:
      - BrowserId=8wGyNsvbR2WNEVaxppnewg;Path=/;Domain=.salesforce.com;Expires=Mon,
        02-Oct-2017 22:35:12 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 03 Aug 2017 22:35:14 GMT
recorded_with: VCR 3.0.3
