---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 06 Feb 2017 22:34:39 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      - reflected-xss block;report-uri /_/ContentDomainCSPNoAuth?type=xss
      Set-Cookie:
      - BrowserId=JOnxMBBxR2SNV59Xp-X__g;Path=/;Domain=.salesforce.com;Expires=Fri,
        07-Apr-2017 22:34:39 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--QA.cs63.my.salesforce.com","id":"https://test.salesforce.com/id/00D6C0000000TrIUAU/0056C000000eBx5QAE","token_type":"Bearer","issued_at":"1486420479830","signature":"QP9G+t4IKKoMbsSUr2gj9+O/jkaeCp8nz1DHChhb770="}'
    http_version:
  recorded_at: Mon, 06 Feb 2017 22:34:39 GMT
- request:
    method: get
    uri: https://sfhousing--qa.cs63.my.salesforce.com/services/apexrest/shortForm/a0tf0000000xw9pAAA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Mon, 06 Feb 2017 22:34:40 GMT
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; frame-ancestors
        ''self'' *.salesforce.com *.force.com; font-src https: data:; connect-src
        ''self'' https:; report-uri /_/ContentDomainCSPNoAuth?type=mydomain; base-uri
        http://sfhousing--qa.cs63.my.salesforce.com/services/apexrest/shortForm/a0tf0000000xw9pAAA'
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="6m4uJ26w5zoo/DLDmYNWG1dWpZ8/GSCPe6SBri8Euw0=";
        max-age=86400; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D6C0000000TrI";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=0_zutEaPQNS-FZ6Q4vO3HQ;Path=/;Domain=.salesforce.com;Expires=Fri,
        07-Apr-2017 22:34:40 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Mon, 06 Feb 2017 22:34:41 GMT
- request:
    method: delete
    uri: https://sfhousing--qa.cs63.my.salesforce.com/services/apexrest/shortForm/delete/a0tf0000000xw9pAAA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Mon, 06 Feb 2017 22:34:42 GMT
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; frame-ancestors
        ''self'' *.salesforce.com *.force.com; font-src https: data:; connect-src
        ''self'' https:; report-uri /_/ContentDomainCSPNoAuth?type=mydomain; base-uri
        http://sfhousing--qa.cs63.my.salesforce.com/services/apexrest/shortForm/delete/a0tf0000000xw9pAAA'
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="6m4uJ26w5zoo/DLDmYNWG1dWpZ8/GSCPe6SBri8Euw0=";
        max-age=86400; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D6C0000000TrI";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=2d8byU9RShyho8oq9e-EHQ;Path=/;Domain=.salesforce.com;Expires=Fri,
        07-Apr-2017 22:34:42 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Mon, 06 Feb 2017 22:34:43 GMT
recorded_with: VCR 3.0.3
