---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 27 Dec 2018 03:29:00 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=Enhs35LwTTmn-7HJy6tx9g;Path=/;Domain=.salesforce.com;Expires=Mon,
        25-Feb-2019 03:29:00 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"<<SALESFORCE_INSTANCE_URL>>","id":"https://test.salesforce.com/id/00D210000009rvpEAA/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1545881340987","signature":"cfWLGg6NK61poMsdAJBaq1lr+PGBRVTmx+A94W25c8c="}'
    http_version: 
  recorded_at: Thu, 27 Dec 2018 03:29:01 GMT
- request:
    method: get
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/shortForm/a0o210000027Yti"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 27 Dec 2018 03:29:01 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D210000009rvpm";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D210000009rvpm";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=qgnUsYk1SKCQiz_9LN49Rw;Path=/;Domain=.salesforce.com;Expires=Mon,
        25-Feb-2019 03:29:01 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Submitted","shortFormPreferences":[{"zip":null,"state":null,"shortformPreferenceID":"a0w21000001hMNiAAM","requiresProof":false,"recordTypeDevName":"COP","preferenceProof":null,"postLotteryValidation":null,"optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvAQAX","individualPreference":null,"city":null,"certificateNumber":null,"appMemberID":null,"applicationID":"a0o210000027YtiAAE","address":null},{"zip":null,"state":null,"shortformPreferenceID":"a0w21000001hMNjAAM","requiresProof":false,"recordTypeDevName":"L_W","preferenceProof":null,"postLotteryValidation":null,"optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvFQAX","individualPreference":null,"city":null,"certificateNumber":null,"appMemberID":null,"applicationID":"a0o210000027YtiAAE","address":null}],"referral":"Email
        Alert","primaryApplicant":{"zip":"94579-1542","yCoordinate":null,"xCoordinate":null,"workInSf":"true","whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":"CA","sexualOrientationOther":null,"sexualOrientation":"Straight/Heterosexual","sexAtBirth":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":"Cell","phone":"4154848715","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":"94579-1542","mailingState":"CA","mailingCity":"SAN
        LEANDRO","mailingAddress":"1476 TROJAN AVE","lastName":"Alvarado","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Miguel","ethnicity":"Hispanic/Latino","email":"imogul@gmail.com","DOB":"1976-10-05","contactId":"0030P000020bdvhQAA","city":"SAN
        LEANDRO","candidateScore":null,"appMemberType":"Primary Applicant","appMemberId":"a0n0P00000AwpIPQAZ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":"1476
        TROJAN AVE"},"otherHousingCounselingAgency":null,"name":"APP-00309238","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00309238","listingID":"a0W0P00000DZTkAUAX","id":"a0o210000027YtiAAE","housingCounselingAgency":null,"householdVouchersSubsidies":"false","householdMembers":[],"hasSenior":null,"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":null,"externalSessionId":"","didApplicantUseHousingCounselingAgency":"No","appRTType":"Rental_Short_Form","applicationSubmittedDate":"2018-12-26","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":75000.00,"alternateContact":null,"agreeToTerms":true,"adaPrioritiesSelected":null}'
    http_version: 
  recorded_at: Thu, 27 Dec 2018 03:29:01 GMT
- request:
    method: delete
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/shortForm/delete/a0o210000027Yti"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 27 Dec 2018 03:29:01 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D210000009rvpm";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D210000009rvpm";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=cWhUtU83T7Sq37E8-gFA-g;Path=/;Domain=.salesforce.com;Expires=Mon,
        25-Feb-2019 03:29:01 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 27 Dec 2018 03:29:02 GMT
recorded_with: VCR 3.0.3
