---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 21 Jul 2017 21:38:28 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - referrer origin-when-cross-origin; upgrade-insecure-requests
      Set-Cookie:
      - BrowserId=c9ogB9GUQMGgBiWsodXe-g;Path=/;Domain=.salesforce.com;Expires=Tue,
        19-Sep-2017 21:38:28 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      - no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs71.my.salesforce.com","id":"https://test.salesforce.com/id/00D4D0000008fvwUAA/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1500673109028","signature":"6c4CfXSaJ0BWRP+5kcSbbPOr6cHKqXrV+eXPY0y0O8Q="}'
    http_version: 
  recorded_at: Fri, 21 Jul 2017 21:38:29 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs71.my.salesforce.com/services/apexrest/shortForm/a0tf0000000xw9pAAA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Fri, 21 Jul 2017 21:38:29 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; max-age=86400;
        report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D4D0000008fvw";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Set-Cookie:
      - BrowserId=17e-6QutRWee6zMLxpu2RA;Path=/;Domain=.salesforce.com;Expires=Tue,
        19-Sep-2017 21:38:29 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 21 Jul 2017 21:38:29 GMT
- request:
    method: delete
    uri: https://sfhousing--full.cs71.my.salesforce.com/services/apexrest/shortForm/delete/a0tf0000000xw9pAAA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Fri, 21 Jul 2017 21:38:29 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; max-age=86400;
        report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D4D0000008fvw";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Set-Cookie:
      - BrowserId=qFhcszjFQK6VbPl2_a-CHg;Path=/;Domain=.salesforce.com;Expires=Tue,
        19-Sep-2017 21:38:29 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 21 Jul 2017 21:38:30 GMT
recorded_with: VCR 3.0.3
