---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jul 2018 23:00:44 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=-QYzEwrVSjWgI-sT7YsUOQ;Path=/;Domain=.salesforce.com;Expires=Sat,
        08-Sep-2018 23:00:44 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs97.my.salesforce.com","id":"https://test.salesforce.com/id/00D0U0000000Qf1UAE/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1531263645588","signature":"Vlql02tEVSeJXJ+clcAa8QHG6Z8m3Gd5cMEgLkjS4T4="}'
    http_version: 
  recorded_at: Tue, 10 Jul 2018 23:00:47 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs97.my.salesforce.com/services/apexrest/shortForm/a0o0U000000brab
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jul 2018 23:00:45 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0U0000000Qf1m";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D0U0000000Qf1m";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=ti67xCVJTm-fRL7-H8Oszw;Path=/;Domain=.salesforce.com;Expires=Sat,
        08-Sep-2018 23:00:45 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"whichOne":null,"totalMonthlyRent":null,"status":"Submitted","shortFormPreferences":[{"zip":null,"state":null,"shortformPreferenceID":"a0w0U000001IJEWQA4","requiresProof":false,"recordTypeDevName":"COP","preferenceProof":null,"postLotteryValidation":null,"optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvAQAX","individualPreference":null,"city":null,"certificateNumber":null,"appMemberID":null,"applicationID":"a0o0U000000brabQAA","address":null},{"zip":null,"state":null,"shortformPreferenceID":"a0w0U000001IJEXQA4","requiresProof":false,"recordTypeDevName":"L_W","preferenceProof":null,"postLotteryValidation":null,"optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvFQAX","individualPreference":null,"city":null,"certificateNumber":null,"appMemberID":null,"applicationID":"a0o0U000000brabQAA","address":null}],"referral":"Email
        Alert","primaryApplicant":{"zip":"94579-1542","yCoordinate":null,"xCoordinate":null,"workInSf":"true","whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":"CA","sexualOrientationOther":null,"sexualOrientation":"Straight/Heterosexual","sexAtBirth":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":"Cell","phone":"4154848715","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":"94579-1542","mailingState":"CA","mailingCity":"SAN
        LEANDRO","mailingAddress":"1476 TROJAN AVE","lastName":"Alvarado","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Miguel","ethnicity":"Hispanic/Latino","email":"imogul@gmail.com","DOB":"1976-10-05","contactId":"0030P000020bdvhQAA","city":"SAN
        LEANDRO","candidateScore":null,"appMemberType":"Primary Applicant","appMemberId":"a0n0P00000AwpIPQAZ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":"1476
        TROJAN AVE"},"other":null,"name":"APP-00230668","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00230668","listingID":"a0W0P00000DZTkAUAX","id":"a0o0U000000brabQAA","householdVouchersSubsidies":"false","householdMembers":[],"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":null,"externalSessionId":"","didApplicantUseHousingCounselingAgency":"No","appRTType":"Rental_Short_Form","applicationSubmittedDate":"2018-07-10","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":75000.00,"alternateContact":null,"agreeToTerms":true,"adaPrioritiesSelected":null}'
    http_version: 
  recorded_at: Tue, 10 Jul 2018 23:00:47 GMT
- request:
    method: delete
    uri: https://sfhousing--full.cs97.my.salesforce.com/services/apexrest/shortForm/delete/a0o0U000000brab
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jul 2018 23:00:46 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0U0000000Qf1m";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D0U0000000Qf1m";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=H9sPtAzGTCOH87QtYcbSFQ;Path=/;Domain=.salesforce.com;Expires=Sat,
        08-Sep-2018 23:00:46 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 10 Jul 2018 23:00:50 GMT
recorded_with: VCR 3.0.3
