---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 14 Mar 2017 17:33:34 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      - reflected-xss block;report-uri /_/ContentDomainCSPNoAuth?type=xss
      Set-Cookie:
      - BrowserId=TVNWUN92RQuZQICGvjJIVw;Path=/;Domain=.salesforce.com;Expires=Sat,
        13-May-2017 17:33:34 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--QA.cs51.my.salesforce.com","id":"https://test.salesforce.com/id/00D4B000000D2n3UAC/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1489512814451","signature":"XLjsni7NZ7qb1a8oHXnHiFJLHmIrRKBYpn1+vXjNWps="}'
    http_version: 
  recorded_at: Tue, 14 Mar 2017 17:33:34 GMT
- request:
    method: get
    uri: https://sfhousing--qa.cs51.my.salesforce.com/services/apexrest/shortForm/a0tf0000000xw9pAAA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Tue, 14 Mar 2017 17:33:34 GMT
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="6m4uJ26w5zoo/DLDmYNWG1dWpZ8/GSCPe6SBri8Euw0=";
        max-age=86400; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D4B000000D2n3";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=gVr1AxrqTxmPhm5EvllF8A;Path=/;Domain=.salesforce.com;Expires=Sat,
        13-May-2017 17:33:34 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 14 Mar 2017 17:33:35 GMT
- request:
    method: delete
    uri: https://sfhousing--qa.cs51.my.salesforce.com/services/apexrest/shortForm/delete/a0tf0000000xw9pAAA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Tue, 14 Mar 2017 17:33:35 GMT
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="6m4uJ26w5zoo/DLDmYNWG1dWpZ8/GSCPe6SBri8Euw0=";
        max-age=86400; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D4B000000D2n3";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=bXo4bLqOSku0_OfaKHq9uA;Path=/;Domain=.salesforce.com;Expires=Sat,
        13-May-2017 17:33:35 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 14 Mar 2017 17:33:36 GMT
recorded_with: VCR 3.0.3
