---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 13 Dec 2017 19:23:26 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=yteeXpT5TpqMywtJv7AszQ;Path=/;Domain=.salesforce.com;Expires=Sun,
        11-Feb-2018 19:23:26 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs95.my.salesforce.com","id":"https://test.salesforce.com/id/00D0x0000008ja8EAA/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1513193006568","signature":"9Fz8+UOa1/8pvgzuJdyO0HyW0iaLPFFB0zcuJVwmZTY="}'
    http_version: 
  recorded_at: Wed, 13 Dec 2017 19:23:26 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs95.my.salesforce.com/services/apexrest/shortForm/a0o0P00000FEUwC
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 13 Dec 2017 19:23:27 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0x0000008ja8";
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=7ywF4EQaTgWhxOJ2xUvtSg;Path=/;Domain=.salesforce.com;Expires=Sun,
        11-Feb-2018 19:23:27 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Submitted","shortFormPreferences":[{"shortformPreferenceID":"a0w0P00000MPK72QAH","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEWvAQAX","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P00000FEUwCQAX","additionalDetails":null},{"shortformPreferenceID":"a0w0P00000MPK9yQAH","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEWvFQAX","ifCombinedIndividualPreference":"Work
        in SF","appMemberID":"a0n0P00000AwpIPQAZ","applicationID":"a0o0P00000FEUwCQAX","additionalDetails":null}],"referral":"Email
        Alert","primaryApplicant":{"zip":"94579-1542","yCoordinate":null,"xCoordinate":null,"workInSf":"true","whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":"CA","sexualOrientationOther":null,"sexualOrientation":"Straight/Heterosexual","sexAtBirth":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":"Cell","phone":"4154848715","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":"94579-1542","mailingState":"CA","mailingCity":"SAN
        LEANDRO","mailingAddress":"1476 TROJAN AVE","lastName":"Alvarado","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Miguel","ethnicity":"Hispanic/Latino","email":"imogul@gmail.com","DOB":"1976-10-05","contactId":"0030P000020bdvhQAA","city":"SAN
        LEANDRO","candidateScore":null,"appMemberType":"Primary Applicant","appMemberId":"a0n0P00000AwpIPQAZ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":"1476
        TROJAN AVE"},"name":"APP-00038757","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038757","listingID":"a0W0P00000DZTkAUAX","id":"a0o0P00000FEUwCQAX","householdVouchersSubsidies":"false","householdMembers":[],"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":"{\"completedSections\":{\"Intro\":true,\"You\":true,\"Household\":true,\"Preferences\":true,\"Income\":true}}","appRTType":"Rental_Short_Form","applicationSubmittedDate":"2017-03-02","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":75000.00,"alternateContact":null,"agreeToTerms":true,"adaPrioritiesSelected":null}'
    http_version: 
  recorded_at: Wed, 13 Dec 2017 19:23:27 GMT
recorded_with: VCR 3.0.3
