---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=dave%40exygy.com.qa&password=XkzG%26h9%5EA%5El%21<<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 07 Sep 2016 18:16:53 GMT
      Strict-Transport-Security:
      - max-age=10886400; includeSubDomains; preload
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; font-src https:
        data:; report-uri /_/ContentDomainCSPNoAuth?type=login'
      Set-Cookie:
      - BrowserId=bjIZtZ8zRMSrg2lDj_2hag;Path=/;Domain=.salesforce.com;Expires=Sun,
        06-Nov-2016 18:16:53 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"00Df0000003aGup!AQ4AQNUU83TTthNZ7v8J33pKonmL.ljHETS6cqP0zXi4m679irfZowBlssDUCdqfeurt_bgyW3BpCj1EC9tZhcFcWevLFKIa","instance_url":"https://sfhousing--qa.cs63.my.salesforce.com","id":"https://test.salesforce.com/id/00Df0000003aGupEAE/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1473272213557","signature":"hhh/45InD0q0JgxYVnhBryNCBC4BH/YOcJP+R6oujCM="}'
    http_version:
  recorded_at: Wed, 07 Sep 2016 18:16:53 GMT
- request:
    method: get
    uri: https://sfhousing--qa.cs63.my.salesforce.com/services/apexrest/shortForm/a0tf0000000xw9pAAA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth 00Df0000003aGup!AQ4AQNUU83TTthNZ7v8J33pKonmL.ljHETS6cqP0zXi4m679irfZowBlssDUCdqfeurt_bgyW3BpCj1EC9tZhcFcWevLFKIa
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 07 Sep 2016 18:16:54 GMT
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; font-src https:
        data:; report-uri /_/ContentDomainCSPNoAuth?type=mydomain'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=9q2EbAXkTIOFBE8bYVzzvg;Path=/;Domain=.salesforce.com;Expires=Sun,
        06-Nov-2016 18:16:54 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"worksInSfPreferenceID":null,"worksInSanFrancisco":false,"workInSfPreferenceProof":null,"workInSfPreferenceNatKey":null,"status":"Submitted","referral":null,"primaryApplicant":{"zip":null,"workInSf":false,"webAppID":"10","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":null,"race":null,"phoneType":"Home","phone":"2022869535","neighborhoodPreferenceMatch":null,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Dolendo","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":false,"genderOther":null,"gender":null,"firstName":"LukesCousin","ethnicity":null,"email":null,"DOB":"1990-07-23","contactId":"003f000000rOokaAAC","city":null,"appMemberId":"a0pf0000002C5P1AAK","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},"neighborhoodResidencePreferenceNatKey":null,"neighborhoodPreferenceProof":null,"neighborhoodPreferenceID":null,"name":"APP-00013653","monthlyIncome":null,"lotteryNumber":"00013653","liveInSfPreferenceProof":null,"liveInSfPreferencePaper":false,"liveInSfPreferenceNatKey":null,"liveInSfPreferenceID":null,"listingID":"a0WU000000CkiM3MAJ","id":"a0tf0000000xw9pAAA","householdVouchersSubsidies":true,"householdMembers":[],"displacedPreferenceNatKey":null,"displacedPreferenceID":null,"certOfPreferenceNatKey":null,"certOfPreferenceID":null,"applicationSubmittedDate":"2016-08-25","applicationSubmissionType":"Electronic","applicationLanguage":"English","annualIncome":20000.00,"alternateContact":null,"agreeToTerms":true}'
    http_version:
  recorded_at: Wed, 07 Sep 2016 18:16:54 GMT
recorded_with: VCR 3.0.3
