---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 29 Jun 2017 00:13:28 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - referrer origin-when-cross-origin; upgrade-insecure-requests
      Set-Cookie:
      - BrowserId=EEDSA-j-Q6mDfxzmfmBqkQ;Path=/;Domain=.salesforce.com;Expires=Mon,
        28-Aug-2017 00:13:28 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      - no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs71.my.salesforce.com","id":"https://test.salesforce.com/id/00D4D0000008fvwUAA/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1498695208419","signature":"b7Br29DqUDouVxa77/aEpABOlWcFk3vs5VHccG8JVUw="}'
    http_version: 
  recorded_at: Thu, 29 Jun 2017 00:13:28 GMT
- request:
    method: post
    uri: https://sfhousing--full.cs71.my.salesforce.com/services/apexrest/shortForm
    body:
      encoding: UTF-8
      string: '{"id":null,"primaryApplicant":{"phone":"2222222222","firstName":"Christine","lastName":"Dolendo","phoneType":"Home","alternatePhone":null,"alternatePhoneType":null,"gender":"Male","dob":"1990-2-2","contactId":null,"webAppID":null},"householdMembers":[{"firstName":"Obie","lastName":"Kanobi","relationship":"Spouse","dob":"1990-7-23"}],"listingID":"a0WU000000ClNXGMA3","referral":"","annualIncome":"20000","applicationSubmissionType":"Electronic","applicationSubmittedDate":"2016-09-07","status":"submitted"}'
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/json
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 29 Jun 2017 00:13:28 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="6m4uJ26w5zoo/DLDmYNWG1dWpZ8/GSCPe6SBri8Euw0=";
        max-age=86400; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D4D0000008fvw";
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; frame-ancestors
        ''self'' *.salesforce.com *.force.com; font-src https: data:; connect-src
        ''self'' https:; report-uri /_/ContentDomainCSP?type=mydomain'
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Set-Cookie:
      - BrowserId=leB0ejENQw2fNgk1CZwuIA;Path=/;Domain=.salesforce.com;Expires=Mon,
        28-Aug-2017 00:13:28 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"worksInSfPreferenceID":null,"workInSfPreferenceProof":null,"workInSfPreferenceNatKey":null,"status":"Submitted","referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":null,"race":null,"phoneType":"Home","phone":"2222222222","noPhone":false,"noEmail":false,"noAddress":false,"neighborhoodPreferenceMatch":null,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Dolendo","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","contactId":"0034D000009DARCQA4","city":null,"candidateScore":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n4D000000Q0HZQA0","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},"neighborhoodResidencePreferenceNatKey":null,"neighborhoodPreferenceProof":null,"neighborhoodPreferenceOptOut":false,"neighborhoodPreferenceID":null,"name":"APP-00039388","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00039388","liveWorkOptOut":false,"liveInSfPreferenceProof":null,"liveInSfPreferencePaper":false,"liveInSfPreferenceNatKey":null,"liveInSfPreferenceID":null,"listingID":"a0WU000000ClNXGMA3","id":"a0o4D0000002WMEQA2","householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":"Spouse","race":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"neighborhoodPreferenceMatch":null,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Kanobi","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","contactId":null,"city":null,"candidateScore":null,"appMemberType":"Household
        Member","appMemberId":"a0n4D000000Q0HYQA0","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null}],"formMetadata":null,"displacedPreferenceOptOut":false,"displacedPreferenceNatKey":null,"displacedPreferenceID":null,"certOfPreferenceOptOut":false,"certOfPreferenceNatKey":null,"certOfPreferenceID":null,"applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false}'
    http_version: 
  recorded_at: Thu, 29 Jun 2017 00:13:30 GMT
recorded_with: VCR 3.0.3
