---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 26 Jul 2017 20:37:23 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - referrer origin-when-cross-origin; upgrade-insecure-requests
      Set-Cookie:
      - BrowserId=bL2mYN6GTVaPthWVx7Hr9Q;Path=/;Domain=.salesforce.com;Expires=Sun,
        24-Sep-2017 20:37:23 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      - no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--QA.cs51.my.salesforce.com","id":"https://test.salesforce.com/id/00D4B000000D2n3UAC/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1501101443614","signature":"51HoAhbiB6vEYC9qThTbwkTEMXClVDd6M1DTSfH7nPE="}'
    http_version: 
  recorded_at: Wed, 26 Jul 2017 20:37:25 GMT
- request:
    method: get
    uri: https://sfhousing--qa.cs51.my.salesforce.com/services/apexrest/shortForm/a0o0P0000093OZE
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 26 Jul 2017 20:37:24 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; max-age=86400;
        report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D4B000000D2n3";
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Set-Cookie:
      - BrowserId=hygpiSWnSvyb-5gdinotZA;Path=/;Domain=.salesforce.com;Expires=Sun,
        24-Sep-2017 20:37:24 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Draft","shortFormPreferences":[{"shortformPreferenceID":"a0z4B000000Z4zQQAS","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK5tQAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"},{"shortformPreferenceID":"a0z4B000000Z4zRQAS","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK5yQAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"},{"shortformPreferenceID":"a0z4B000000Z4zSQAS","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK63QAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"},{"shortformPreferenceID":"a0z4B000000Z4zTQAS","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK68QAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"}],"referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":"1","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":"Home","phone":"2222222222","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Dolendo","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","contactId":"0030P00001y3eLHQAY","city":null,"candidateScore":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AONbEQAX","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},"name":"APP-00016070","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00016070","listingID":"a0W0P00000DZ4dTUAT","id":"a0o0P0000093OZEQA2","householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":"Spouse","race":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Kanobi","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","contactId":null,"city":null,"candidateScore":null,"appMemberType":"Household
        Member","appMemberId":"a0n4B000000Ff06QAC","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null}],"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":null,"appRTType":"Rental_Short_Form","applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false,"adaPrioritiesSelected":null}'
    http_version: 
  recorded_at: Wed, 26 Jul 2017 20:37:25 GMT
- request:
    method: post
    uri: https://sfhousing--qa.cs51.my.salesforce.com/services/apexrest/shortForm
    body:
      encoding: UTF-8
      string: '{"id":"a0o0P0000093OZE","primaryApplicant":{"phone":"2222222222","firstName":"Christine","lastName":"Dolendo","phoneType":"Home","alternatePhone":null,"alternatePhoneType":null,"gender":"Male","dob":"1990-2-2","contactId":"0030P00001y3eLHQAY","webAppID":1},"householdMembers":[{"firstName":"Obie","lastName":"Kanobi","relationship":"Spouse","dob":"1990-7-23"}],"listingID":"a0WU000000ClNXGMA3","referral":"","annualIncome":"20000","applicationSubmissionType":"Electronic","applicationSubmittedDate":"2016-09-07","status":"draft"}'
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/json
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 26 Jul 2017 20:37:24 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; max-age=86400;
        report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D4B000000D2n3";
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; frame-ancestors
        ''self'' *.salesforce.com *.force.com; font-src https: data:; connect-src
        ''self'' https:; report-uri /_/ContentDomainCSP?type=mydomain'
      Content-Security-Policy:
      - referrer origin-when-cross-origin
      Set-Cookie:
      - BrowserId=eI2wSIZUSm-nPm_tyZw0zA;Path=/;Domain=.salesforce.com;Expires=Sun,
        24-Sep-2017 20:37:24 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Draft","shortFormPreferences":[{"shortformPreferenceID":"a0z4B000000ZeatQAC","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK5tQAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"},{"shortformPreferenceID":"a0z4B000000ZeauQAC","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK5yQAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"},{"shortformPreferenceID":"a0z4B000000ZeavQAC","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK63QAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"},{"shortformPreferenceID":"a0z4B000000ZeawQAC","preferenceProof":null,"optOut":false,"naturalKey":null,"listingPreferenceID":"a0l0P00001JEK68QAH","ifCombinedIndividualPreference":null,"appMemberID":null,"applicationID":"a0o0P0000093OZEQA2"}],"referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":"1","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":"Home","phone":"2222222222","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Dolendo","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","contactId":"0030P00001y3eLHQAY","city":null,"candidateScore":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AONbEQAX","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},"name":"APP-00016070","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00016070","listingID":"a0W0P00000DZ4dTUAT","id":"a0o0P0000093OZEQA2","householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":"Spouse","race":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Kanobi","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","contactId":null,"city":null,"candidateScore":null,"appMemberType":"Household
        Member","appMemberId":"a0n4B000000Ff06QAC","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null}],"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":null,"appRTType":"Rental_Short_Form","applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false,"adaPrioritiesSelected":null}'
    http_version: 
  recorded_at: Wed, 26 Jul 2017 20:37:31 GMT
recorded_with: VCR 3.0.3
