---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=dave%40exygy.com.qa&password=XkzG%26h9%5EA%5El%21<<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 27 Sep 2016 14:46:10 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=LGXky521Qby9b7xM2Ay0Rw;Path=/;Domain=.salesforce.com;Expires=Sat,
        26-Nov-2016 14:46:10 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"00Df0000003aGup!AQ4AQFx_GSFApf1XEalHpx.lhkj_MGFxP4z6NoQux13Tuc5tsZmZ5eKLImrIqR4lCyqlZIx4CswOUvrDcnOswbQd4SVBmK9X","instance_url":"https://sfhousing--QA.cs16.my.salesforce.com","id":"https://test.salesforce.com/id/00Df0000003aGupEAE/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1474987571187","signature":"HIVqem1QUHbqBDiTXccqbMwLBEmSJw22FkRdTHFDTgg="}'
    http_version:
  recorded_at: Tue, 27 Sep 2016 14:46:11 GMT
- request:
    method: get
    uri: https://sfhousing--qa.cs16.my.salesforce.com/services/apexrest/shortForm/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth 00Df0000003aGup!AQ4AQFx_GSFApf1XEalHpx.lhkj_MGFxP4z6NoQux13Tuc5tsZmZ5eKLImrIqR4lCyqlZIx4CswOUvrDcnOswbQd4SVBmK9X
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Tue, 27 Sep 2016 14:46:12 GMT
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; font-src https:
        data:; report-uri /_/ContentDomainCSPNoAuth?type=mydomain'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=7znH-zO9SlO-bfxGrKH6xw;Path=/;Domain=.salesforce.com;Expires=Sat,
        26-Nov-2016 14:46:12 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Tue, 27 Sep 2016 14:46:12 GMT
- request:
    method: post
    uri: https://sfhousing--qa.cs16.my.salesforce.com/services/apexrest/shortForm
    body:
      encoding: UTF-8
      string: '{"id":null,"primaryApplicant":{"phone":"2222222222","firstName":"Christine","lastName":"Dolendo","phoneType":"Home","alternatePhone":null,"alternatePhoneType":null,"gender":"Male","dob":"1990-2-2","contactId":null,"webAppID":null},"householdMembers":[{"firstName":"Obie","lastName":"Kanobi","relationship":"Spouse","dob":"1990-7-23"}],"listingID":"a0WU000000ClNXGMA3","referral":"","annualIncome":"20000","applicationSubmissionType":"Electronic","applicationSubmittedDate":"2016-09-07","status":"submitted"}'
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/json
      Authorization:
      - OAuth 00Df0000003aGup!AQ4AQFx_GSFApf1XEalHpx.lhkj_MGFxP4z6NoQux13Tuc5tsZmZ5eKLImrIqR4lCyqlZIx4CswOUvrDcnOswbQd4SVBmK9X
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 27 Sep 2016 14:46:12 GMT
      Content-Security-Policy-Report-Only:
      - 'default-src https:; script-src https: ''unsafe-inline'' ''unsafe-eval'';
        style-src https: ''unsafe-inline''; img-src https: data:; font-src https:
        data:; report-uri /_/ContentDomainCSPNoAuth?type=mydomain'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Set-Cookie:
      - BrowserId=89UHzqARSLOIMjP51eYWCQ;Path=/;Domain=.salesforce.com;Expires=Sat,
        26-Nov-2016 14:46:12 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"worksInSfPreferenceID":null,"worksInSanFrancisco":false,"workInSfPreferenceProof":null,"workInSfPreferenceNatKey":null,"status":"Submitted","referral":null,"primaryApplicant":{"zip":null,"workInSf":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":null,"race":null,"phoneType":"Home","phone":"2222222222","noPhone":false,"noEmail":false,"noAddress":false,"neighborhoodPreferenceMatch":null,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Dolendo","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","contactId":"003f000000rZhVXAA0","city":null,"appMemberId":"a0pf0000002L44CAAS","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},"neighborhoodResidencePreferenceNatKey":null,"neighborhoodPreferenceProof":null,"neighborhoodPreferenceID":null,"name":"APP-00035080","monthlyIncome":null,"lotteryNumber":"00035080","liveInSfPreferenceProof":null,"liveInSfPreferencePaper":false,"liveInSfPreferenceNatKey":null,"liveInSfPreferenceID":null,"listingID":"a0WU000000ClNXGMA3","id":"a0tf0000000SjLNAA0","householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"workInSf":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"relationship":"Spouse","race":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"neighborhoodPreferenceMatch":null,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Kanobi","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","contactId":null,"city":null,"appMemberId":"a0pf0000002L44DAAS","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null}],"formMetadata":null,"displacedPreferenceNatKey":null,"displacedPreferenceID":null,"certOfPreferenceNatKey":null,"certOfPreferenceID":null,"applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false}'
    http_version:
  recorded_at: Tue, 27 Sep 2016 14:46:20 GMT
recorded_with: VCR 3.0.3
