---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Mar 2018 22:38:50 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=QjFqo8afR6aZTJ5q3ZYu_g;Path=/;Domain=.salesforce.com;Expires=Tue,
        29-May-2018 22:38:50 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs95.my.salesforce.com","id":"https://test.salesforce.com/id/00D0x000000CtkoEAC/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1522449530947","signature":"CCF1me8QtTkJnDRe68l4osvlab+W/i3XYZtNGJ5Rl2c="}'
    http_version: 
  recorded_at: Fri, 30 Mar 2018 22:38:50 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs95.my.salesforce.com/services/apexrest/shortForm/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Fri, 30 Mar 2018 22:38:51 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D0x000000Ctkop";
      Expect-Ct:
      - max-age=0; report-uri="https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00D0x000000Ctkop";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=DJztreatSNCZIqYuy-qItw;Path=/;Domain=.salesforce.com;Expires=Tue,
        29-May-2018 22:38:51 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 30 Mar 2018 22:38:51 GMT
recorded_with: VCR 3.0.3
